# mcs-dns-check.yaml
apiVersion: v1
kind: Pod
metadata:
  name: dns-validator
  namespace: default
  labels:                
    environment: production
    app: dns-validator
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "infinite"]
