apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: genidsvc-api-route
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`genidsvc.ingress`)
    kind: Rule
    services:
    - name: genidsvc-dapr # Pointing to the sidecar
      port: 3500