apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: amqp://rabbitmq.default.svc.cluster.local:5672
    - name: username
      secretKeyRef:
        name: rmq-auth
        key: RABBITMQ_DEFAULT_USER
    - name: password
      secretKeyRef:
        name: rmq-auth
        key: RABBITMQ_DEFAULT_PASS
auth:
  secretStore: kubernetes