apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: rmq-auth
        key: RABBITMQ_CONNECTION_STRING
auth:
  secretStore: kubernetes